version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"

  blocklist:
    image: blinkspark/blocklist:latest
    volumes:
      - "./blocklist.txt:/blocklist.txt"
